unique_ids:
  assets:
    standard-page.html: WOFILOLJW5SPDFOA6MWWQWCW7TKKHF5Q
    theme.css: CJEEPMKZF5ZV5UWC5LDNYATXCZUSVGST
  forms:
    Form1: YFLJSQODCDGEC3UPT5H2YVRQAI6H6DUR
  modules: {}
  scripts: {}
  server_modules: {}
